blank_issues_enabled: false
contact_links:
  - name: Get Help or Ask a Question
    url: https://github.com/your-username/qrux/discussions/new?category=q-a
    about: If you can't get something to work the way you expect, open a question in our discussion forums.

  - name: Feature Request
    url: https://github.com/your-username/qrux/discussions/new?category=ideas
    about: "Suggest any ideas you have for new features or improvements."

  - name: Documentation Issue
    url: https://github.com/your-username/qrux/issues/new?template=bug_report.md&title=%5BDocs%5D%3A+
    about: "For documentation issues, please file an issue and prefix the title with [Docs]."
